export const After10th = ["Diploma in Computer Science And Engineering", "Diploma in Information Technology", "Diploma in Civil Engineering", "Diploma in Mechanical Engineering", "Diploma in Electrical Engineering", "Diploma in Artificial Intelligence (AI) & Machine Learning (ML)", "Diploma in Information & Communication Technology (ICT)", "Diploma in Computer Engineering", "Diploma in Chemical Engineering", "Diploma in Aeronautical Engineering"]

export const Science12th = ["B.Tech in Computer Science And Engineering", "B.Tech in Information Technology", "B.Tech in Civil Engineering", "B.Tech in Mechanical Engineering", "B.Tech in Electrical Engineering", "B.Tech in Food Technology", "B.Tech in Chemical Engineering", "B.Tech in Aeronautical Engineering", "B.Tech in Biomedical Engineering", "B.Tech in Computer Engineering", "B.Tech in Computer Engineering (Artificial Intelligence)", "B.Tech in Computer Engineering (Cyber Security)", "B. Pharm", "Bachelor of Physiotherapy - BPT", "B.A.M.S", "GNM", "B.Sc in Nursing (UG)", "B.Sc in Phy. Chem & Maths - A Group", "B.Sc in Chem. Biotech & Micro - B Group", "B.Sc in Nutrition & Dietetics", "B.Sc in Cell & Molecular Biology", "B.B.A.(Honours)", "B.Com (Honours)", "B.Com (Honours) in Wealth Management & Computerised GST", "B.A. (Honours) in Psychology / Sociology / English / Public Administration / Economics", "Bachelor of Arts in Culinary Arts", "Bachelor of Arts in Journalism and Mass - Communication", "Bachelor of Performing Arts (Music, Dance and Drama)", "Bachelor of Design (Fashion Design & Technology)"]

export const Commerce12th = ["GNM", "B.B.A.(Honours)", "B.Com (Honours)", "B.Com (Honours) in Wealth Management & Computerised GST", "B.A. (Honours) in Psychology / Sociology / English / Public Administration / Economics", "Bachelor of Arts in Culinary Arts", "Bachelor of Arts in Journalism and Mass - Communication", "Bachelor of Performing Arts (Music, Dance and Drama)", "Bachelor of Design (Fashion Design & Technology)"]

export const Arts12th = ["Diploma in Computer Science And Engineering", "Diploma in Information Technology", "Diploma in Civil Engineering", "Diploma in Mechanical Engineering", "Diploma in Electrical Engineering", "Diploma in Artificial Intelligence (AI) & Machine Learning (ML)", "Diploma in Information & Communication Technology (ICT)", "Diploma in Computer Engineering", "Diploma in Chemical Engineering", "Diploma in Aeronautical Engineering"]

export const AfterDiplomaEngineeringD2D = ["Diploma to Degree (D2D) Electrical Engineering", "Diploma to Degree (D2D) Civil Engineering", "Diploma to Degree (D2D) Mechanical Engineering", "Diploma to Degree (D2D) Information Technology", "Diploma to Degree (D2D) Computer Science & Engineering"]

export const AfterItiC2D = ["Certificate Course to Diploma (C2D) Electrical Engineering", "Certificate Course to Diploma (C2D) Civil Engineering", "Certificate Course to Diploma (C2D) Mechanical Engineering", "Certificate Course to Diploma (C2D) Information Technology", "Certificate Course to Diploma (C2D)  Computer Science & Engineering"]

export const AfterGraduation = ["MPT in Musculoskeletal & Sports", "MPT in Neurological & Psychosomatic disorders", "MPT in Cardiorespiratory & Intensive Care", "M.Tech in Data Science", "M.Tech in Advance in Manufacturing System", "M.Tech in Computer Science & Engineering", "M.Tech in Computer Engineering", "M.Tech in Electrical Engineering", "M.Tech in Information Technology", "MBA (PG)", "MBA in Innovation, Entrepreneurship & Venture Development (PG)", "M.Pharm in Pharmaceutics", "M.Pharm in Pharmacology", "M.Pharm in Pharmaceutical Quality Assurance", "M.Pharm in Pharmaceutical Technology", "M.Sc in Nutrition & Dietetics", "M.Sc in Cell & Molecular Biology", "M.B.A.", "M.B.A. (Executive) for working professional only", "M.B.A. in Healthcare Management & Hospital  Administration"]

export const AfterMasters = ["Diploma to Degree (D2D) Electrical Engineering", "Diploma to Degree (D2D) Civil Engineering", "Diploma to Degree (D2D) Mechanical Engineering", "Diploma to Degree (D2D) Information Technology", "Diploma to Degree (D2D) Computer Science & Engineering"]